source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "minimal-mistakes-jekyll"
gem "webrick"
gem "tzinfo-data"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-include-cache"
end
