name: Deploy Jekyll site to external repository

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: './website'

      - name: Build with Jekyll
        run: |
          cd website
          bundle install
          bundle exec jekyll build

      - name: Deploy to daniloalsilva/whichbike.com
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: daniloalsilva/whichbike.com
          publish_branch: main
          publish_dir: ./website/_site
